"""Evidence Builder agent.

Binds each business claim to exactly one CalculationResult produced by the
Data Analyst. The LLM contributes only the claim's human-readable wording
and an initial confidence estimate; every other field on the resulting
Evidence object — source_operation, source_columns, filters, calculation
(the reproducible expression), and result — is copied directly from the
bound CalculationResult by this code, never generated by the model. This
is what makes the insight -> claim -> calculation -> data trace mechanical
rather than a matter of trusting the model to transcribe a number
correctly.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass

from app.llm.client import LLMClient
from app.models.calculation import CalculationResult
from app.models.evidence import Evidence


@dataclass
class EvidenceItem:
    """Pairs an Evidence with the exact CalculationResult it was bound to,
    so downstream stages (Verification) can recompute against the original
    operation/parameters instead of re-deriving them from Evidence's
    reduced, report-facing field set."""

    evidence: Evidence
    calculation: CalculationResult

SYSTEM_PROMPT = (
    "You are writing evidence-backed claims for a business report. You will "
    "be given a numbered list of calculation results that were already "
    "computed by deterministic code. For each claim worth reporting, submit "
    "it via submit_evidence, referencing the calculation_index of the single "
    "calculation result it is based on. Do not restate or alter the numeric "
    "result yourself — write the claim in plain business language and let "
    "the system attach the exact number. Assign a confidence between 0 and 1 "
    "reflecting how directly the calculation supports the claim: a plain "
    "aggregation supports a descriptive claim with high confidence, but a "
    "causal or explanatory claim should get a lower confidence even when the "
    "underlying arithmetic is precise, since precision of the number does "
    "not establish the cause."
)

EVIDENCE_TOOL = {
    "name": "submit_evidence",
    "description": "Submit one or more evidence-backed claims, each tied to exactly one calculation result.",
    "input_schema": {
        "type": "object",
        "properties": {
            "evidence_items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "claim": {"type": "string"},
                        "calculation_index": {"type": "integer"},
                        "confidence": {"type": "number", "minimum": 0, "maximum": 1},
                    },
                    "required": ["claim", "calculation_index", "confidence"],
                },
            }
        },
        "required": ["evidence_items"],
    },
}


def _format_calculations(calculations: list[CalculationResult]) -> str:
    lines = []
    for i, calc in enumerate(calculations):
        filters_repr = [f.model_dump() for f in calc.filters]
        lines.append(
            f"[{i}] operation={calc.operation} columns={calc.input_columns} "
            f"filters={filters_repr} result={calc.result} expression={calc.reproducible_expression}"
        )
    return "\n".join(lines)


def build_evidence(
    calculations: list[CalculationResult], question: str, llm_client: LLMClient
) -> list[EvidenceItem]:
    if not calculations:
        return []

    user_message = (
        f"Business question: {question}\n\n"
        f"Calculation results (0-indexed):\n{_format_calculations(calculations)}"
    )
    response = llm_client.create_message(
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_message}],
        tools=[EVIDENCE_TOOL],
        tool_choice={"type": "tool", "name": "submit_evidence"},
        max_tokens=2048,
    )

    if not response.tool_calls:
        raise ValueError("Evidence Builder did not return structured evidence via submit_evidence")

    raw_items = response.tool_calls[0].input.get("evidence_items", [])
    evidence_list: list[EvidenceItem] = []
    for item in raw_items:
        idx = item["calculation_index"]
        if not (0 <= idx < len(calculations)):
            raise ValueError(f"Evidence references invalid calculation_index {idx}")
        calc = calculations[idx]
        evidence = Evidence(
            evidence_id=f"ev_{uuid.uuid4().hex[:8]}",
            claim=item["claim"],
            source_operation=calc.operation,
            source_columns=calc.input_columns,
            filters=calc.filters,
            calculation=calc.reproducible_expression,
            result=calc.result,
            confidence=item["confidence"],
        )
        evidence_list.append(EvidenceItem(evidence=evidence, calculation=calc))
    return evidence_list
